services:
  api-test:
    image: nginx
  api.test:
    image: nginx
  api:
    image: nginx
  analytics:
    image: nginx
    environment:
      - API_URL=$SERVICE_URL_API
      - ANOTHER_URL=$SERVICE_FQDN_ANOTHER_SERVICE
  another-service:
    image: nginx
    environment:
      - API_FQDN=$SERVICE_FQDN_API
