services:
  web1:
    image: 'nginx:alpine'
    volumes:
      - '/data/coolify/test/data/index1.html:/usr/share/nginx/html/index.html:ro'
  web2:
    image: 'nginx:alpine'
    volumes:
      - '/data/coolify/test/data/index2.html:/usr/share/nginx/html/index.html:ro'
