services:
  web:
    container_name: web
    image: nginx
    restart: unless-stopped
    volumes:
      - 'static-data:/var/www/html:ro'
    expose:
      - '80'
      - '443'
    depends_on:
      - app
  app:
    container_name: app
    image: nginx
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - 'static-data:/var/www/html'

